### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by tsinis** [codemagic-ci-cd/flutter-desktop-docker#2]
Hey Codemagic Team!

I'm not sure I'm writing in the right section, but apparently, the Linux builds are broken. I created the simplest example, 8 lines of code app, just to show the issue. Here is my repository:
https://github.com/tsinis/codemagic
There is a build.zip file from the building on Ubuntu 20.1 LTS, and the correct build log in the root of repo. And below you can see the build error log from the Codemagic: 
https://codemagic.io/app/5fcd4dc959d78f8de3d0af97/build/5fce84867cc398000a7d0590

Anyways thank you for your great service! It's a lifesaver.

**Comment by VeArnold** [comment]
Hey Tsinis!

We'll take a look and try to reproduce. 

Thanks for reporting!

**Comment by tsinis** [comment]
> Hey Tsinis!
> 
> 
> 
> We'll take a look and try to reproduce. 
> 
> 
> 
> Thanks for reporting!

Thanks @VeArnold  project is created on latest master, but I believe it will be reproducible on beta/dev too.

**Comment by VeArnold** [comment]
@tsinis Hey, we deployed some updates to the docker, and our builds seem to go through now. Please feel free to open, if the problem persists.
